name: Build GitHub Pages site
env:
  NODE_ENV: development
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Build Site
        run: npm run build:demo
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo-dist
